### ISSUE TITLE
Remark while installing

### ISSUE THREAD

**Issue by krishmurjani** [saagarjha/unxip#12]
Hi. This is what it's showing me when I'm trying to install it.

`<unknown>:0: remark: did not find a prebuilt standard library for target 'x86_64-apple-macos' compatible with this Swift compiler; building it may take a few minutes, but it should only happen once for this combination of compiler and target`

**Comment by saagarjha** [comment]
I reproduced this on a new machine and it's just there to tell you that the compilation may take longer than usual. I don't think this is a bug, so I'm going to close this–let me know if you feel otherwise.
