### ISSUE TITLE
Fails to extract Xcode 12.4

### ISSUE THREAD

**Issue by kode54** [saagarjha/unxip#17]
As titled, it manages to extract Xcode 12.4 to 2.04GB worth of broken app bundle and nothing more. Perhaps I failed to download it correctly?

**Comment by saagarjha** [comment]
I just downloaded and ran unxip against [Xcode_13.4.xip](https://download.developer.apple.com/Developer_Tools/Xcode_13.4/Xcode_13.4.xip) and it seems to have worked for me. Did it fail with an error or crash partway through? Do you have enough disk space to complete the extraction?

**Comment by saagarjha** [comment]
Hi, I just pushed https://github.com/saagarjha/unxip/commit/ab0ccc398bf91e01e8ddb563e649a9584db05684 to fix an issue with directory creation that you might've been running into. Can you try it and see if fixes the issue for you?

**Comment by kode54** [comment]
Yeah, it extracts now. I don't know if I had a faulty archive or what, this time I had a fresh download and it extracted.

**Comment by saagarjha** [comment]
Thanks for confirming! This one was probably my fault :)
