### ISSUE TITLE
Normal to see "File exists" in output?

### ISSUE THREAD

**Issue by NorseGaud** [saagarjha/unxip#19]
When I run `unxip`, I see my terminal spammed with 

```
creating directory at ./Xcode.app/Contents/Developer/Applications/Xcode Server Builder.app/Contents/MacOS failed: File exists
creating directory at ./Xcode.app/Contents/Developer/Applications/Xcode Server Builder.app/Contents/XPCServices/XCSPortalService.xpc/Contents/_CodeSignature failed: File exists
```

This normal?

**Comment by NorseGaud** [comment]
I must have unxiped it already somehow... It only happens when the Xcode.app exists... Ignore :)

**Comment by saagarjha** [comment]
Yep, unxip follows the UNIX philosophy of not checking for errors and not doing anything but it’s core functionality, such as actually bothering to move files out of the way if they conflict ;)
