### ISSUE TITLE
add -v / --version flags

### ISSUE THREAD

**Issue by luckman212** [saagarjha/unxip#22]
Amazing utility! @saagarjha 

Would you consider adding a commandline switch to print the version? (`-v/--version`)

I would like to include this tool in some build scripts etc so it would be useful to be able to check if the correct version was installed already.

**Comment by saagarjha** [comment]
Well I just used -v for verbose but as I haven’t cut a release yet I can repurpose that flag: https://github.com/saagarjha/unxip/blob/2522f56661f0d0ab08d40fa6a3bef2c04c1d29fa/unxip.swift#L239

**Comment by saagarjha** [comment]
-V seemed to be more conventional, so I used it instead.

**Comment by saagarjha** [comment]
This is shipping in https://github.com/saagarjha/unxip/releases/tag/v1.1.2.
