### ISSUE TITLE
Output argument

### ISSUE THREAD

**Issue by alessaba** [saagarjha/unxip#3]
It would be a nice addition if it was possible to specify an output path for the extracted file. It is easily doable with a mv, but skipping the move to have it directly where it belongs would be better

**Comment by saagarjha** [comment]
Yep, this is my list to add and shouldn't be too hard.

**Comment by saagarjha** [comment]
Fixed in https://github.com/saagarjha/unxip/commit/415f5cada0373b54e5f7e98f2396163a9ff21980.
