### ISSUE TITLE
header error how to fix

### ISSUE THREAD

**Issue by eliekh05** [saagarjha/unxip#6]
swiftc -parse-as-library -O unxip.swift 
  
/usr/local/include/module.modulemap:15:9: error: header 'compression.h' not found
 header "compression.h"
        ^
<unknown>:0: error: could not build Objective-C module 'Compression'

**Comment by saagarjha** [comment]
What’s your environment? Do you have Xcode or the command line tools installed? Which OS are you on?

**Comment by eliekh05** [comment]
the macOS 12 default and yes i have xcode and command lines and i am on macOS 12.2 (non beta)

**Comment by saagarjha** [comment]
Are you able to import Compression from, say, the Swift REPL?

**Comment by eliekh05** [comment]
no

**Comment by saagarjha** [comment]
I feel like your command line tools are probably not working correctly. Can you check what `xcode-select -p` reports? Does `sudo xcode-select --install` help?

**Comment by eliekh05** [comment]
check this pictur
<img width="567" alt="Screen Shot 2022-02-23 at 3 41 56 PM" src="https://user-images.githubusercontent.com/67870780/155331319-379dc857-c3d9-457a-b113-6b31314a3183.png">
e

**Comment by eliekh05** [comment]
> check this picture
> 
> <img width="567" alt="Screen Shot 2022-02-23 at 3 41 56 PM" src="https://user-images.githubusercontent.com/67870780/155331319-379dc857-c3d9-457a-b113-6b31314a3183.png">
> 
> 

so what is the solution

**Comment by saagarjha** [comment]
Can you running `DEVELOPER_DIR=/Library/Developer/CommandLineTools swiftc -parse-as-library -O unxip.swift`?

**Comment by eliekh05** [comment]
> Can you running `DEVELOPER_DIR=/Library/Developer/CommandLineTools swiftc -parse-as-library -O unxip.swift`?

not work

**Comment by eliekh05** [comment]
it worked

**Comment by saagarjha** [comment]
Awesome! It seems like your Xcode installation was probably broken, you should probably replace it with the newly-extracted Xcode you just generated.

I'm going to close this issue, but if you think your problem isn't fixed yet feel free to reopen it!
